### ISSUE TITLE
[suggestion] using pretty url

### ISSUE THREAD

**Issue by nelson6e65** [themanaworld/themanaworld-website#15]
The `index.php` part in the URLs makes uggly the Wiki.

**Comment by mekolat** [comment]
I've said that to wushin countless times

**Comment by nelson6e65** [comment]
I made pretty URLs and published here: http://tmw.nelson6e65.xyz

Check this url examples for Main Page:
http://tmw.nelson6e65.xyz/view/Main_Page
http://tmw.nelson6e65.xyz/edit/Main_Page
http://tmw.nelson6e65.xyz/history/Main_Page
http://tmw.nelson6e65.xyz/delete/Main_Page
http://tmw.nelson6e65.xyz/view/Special:MovePage/Main_Page
http://tmw.nelson6e65.xyz/unprotect/Main_Page

This is what I made:
https://github.com/spicy-tmw/themanaworld-website/compare/3f8b0c844f36d277b595206bec22e3d61f175685...spicy-tmw:011be86224e8ddf9d43a605565a5f5b1edf5b795

I think is not really hard to implement.
**It would be nice in TMW page!** :smiley:

**Comment by mekolat** [comment]
you don't even need the `/view` part

**Comment by nelson6e65** [comment]
Yes, I was about to use like that, but... https://www.mediawiki.org/wiki/Manual:Wiki_in_site_root_directory#MediaWiki_on_dedicated_servers_with_wiki-specific_domain_.28or_subdomain.29_names

**Comment by wushin** [comment]
We use nginx so one would also have to change the rewrite methods.

**Comment by nelson6e65** [comment]
:+1:

**Comment by wushin** [comment]
@nelson6e65 can you come up with a nginx example and I could test it?

**Comment by nelson6e65** [comment]
@wushin, I never used nginx. u.u
Maybe in the night if I got som time...

But you can check this resources:
https://www.mediawiki.org/wiki/Manual:Short_URL/
http://shorturls.redwerks.org/
